# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invertedindex.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='invertedindex.proto',
  package='invertedindex',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13invertedindex.proto\x12\rinvertedindex\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\x05\"\x15\n\x07IdArray\x12\n\n\x02id\x18\x01 \x03(\x05\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\xaf\x01\n\rInvertedIndex\x12/\n\x03\x61\x64\x64\x12\x13.invertedindex.Text\x1a\x11.invertedindex.Id\"\x00\x12\x37\n\x06search\x12\x13.invertedindex.Text\x1a\x16.invertedindex.IdArray\"\x00\x12\x34\n\x06\x64\x65lete\x12\x11.invertedindex.Id\x1a\x15.invertedindex.Status\"\x00\x62\x06proto3')
)




_ID = _descriptor.Descriptor(
  name='Id',
  full_name='invertedindex.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='invertedindex.Id.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=54,
)


_IDARRAY = _descriptor.Descriptor(
  name='IdArray',
  full_name='invertedindex.IdArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='invertedindex.IdArray.id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=77,
)


_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='invertedindex.Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='invertedindex.Text.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=99,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='invertedindex.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='invertedindex.Status.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['Id'] = _ID
DESCRIPTOR.message_types_by_name['IdArray'] = _IDARRAY
DESCRIPTOR.message_types_by_name['Text'] = _TEXT
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), dict(
  DESCRIPTOR = _ID,
  __module__ = 'invertedindex_pb2'
  # @@protoc_insertion_point(class_scope:invertedindex.Id)
  ))
_sym_db.RegisterMessage(Id)

IdArray = _reflection.GeneratedProtocolMessageType('IdArray', (_message.Message,), dict(
  DESCRIPTOR = _IDARRAY,
  __module__ = 'invertedindex_pb2'
  # @@protoc_insertion_point(class_scope:invertedindex.IdArray)
  ))
_sym_db.RegisterMessage(IdArray)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), dict(
  DESCRIPTOR = _TEXT,
  __module__ = 'invertedindex_pb2'
  # @@protoc_insertion_point(class_scope:invertedindex.Text)
  ))
_sym_db.RegisterMessage(Text)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'invertedindex_pb2'
  # @@protoc_insertion_point(class_scope:invertedindex.Status)
  ))
_sym_db.RegisterMessage(Status)



_INVERTEDINDEX = _descriptor.ServiceDescriptor(
  name='InvertedIndex',
  full_name='invertedindex.InvertedIndex',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=128,
  serialized_end=303,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='invertedindex.InvertedIndex.add',
    index=0,
    containing_service=None,
    input_type=_TEXT,
    output_type=_ID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='search',
    full_name='invertedindex.InvertedIndex.search',
    index=1,
    containing_service=None,
    input_type=_TEXT,
    output_type=_IDARRAY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='invertedindex.InvertedIndex.delete',
    index=2,
    containing_service=None,
    input_type=_ID,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INVERTEDINDEX)

DESCRIPTOR.services_by_name['InvertedIndex'] = _INVERTEDINDEX

# @@protoc_insertion_point(module_scope)
